version: '3.8'

services:
  flask:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"
    environment:
      - IMMUNOLYSER_DATA=/data
      - IS_DOCKER=true
    volumes:
      - ./data_files:/data
      - ./tools:/tools
      - ./data_files_2:/app/Immunolyser/app/static/images  # <== Added bind mount
    command: ["flask"]
    depends_on:
      - redis

  celery:
    build: .
    container_name: celery_worker
    environment:
      - IMMUNOLYSER_DATA=/data
      - IS_DOCKER=true
    volumes:
      - ./data_files:/data
      - ./tools:/tools
      - ./data_files_2:/app/Immunolyser/app/static/images  # <== Added bind mount
    command: ["celery"]
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
