#! /bin/tcsh -f

# This the main NetMHC 4.0 script. It only acts as the frontend to the
# software proper, a compiled binary.
# 
# VERSION:	2015 June 02	launch
# 

###############################################################################
#               GENERAL SETTINGS: CUSTOMIZE TO YOUR SITE
###############################################################################

# full path to the NetMHCpan 2.8 directory (mandatory)
setenv	NMHOME	/mnt/c/Users/ASUS/Documents/sem3/thesis/firstdemo/app/tools/netMHC-4.0

# determine where to store temporary files (must be writable to all users)

if ( ${?TMPDIR} == 0 ) then
	setenv  TMPDIR  /scratch
endif

# determine platform (do not change this unless you don't have 'uname'!)
setenv	UNIX	`uname -s`
setenv	AR	`uname -m`

###############################################################################
#               NOTHING SHOULD NEED CHANGING BELOW THIS LINE!
###############################################################################

# other settings
set PLATFORM = `echo $UNIX $AR | awk '{print $1"_"$2}'`
setenv NETMHC $NMHOME/$PLATFORM

# main ========================================================================
if ( -x $NETMHC/bin/netMHC ) then
   $NETMHC/bin/netMHC $*
else
   echo netMHC: no binaries found for $PLATFORM $NETMHC/bin/netMHC
endif

# end of script ===============================================================
